# Generated by Django 3.2.5 on 2021-07-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_publ', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_publ', models.DateTimeField(auto_now=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
    ]
